### ISSUE TITLE
Graveyard is just a black screen

### ISSUE THREAD

**Issue by revsuine** [zephyo/YOU-LEFT-ME.#1]
Okay, so I played this a few times so I'm not entirely sure what I clicked, but here's as much as I remember:

**OS:** Ubuntu 16.04. Vanilla, Unity desktop, using a GTX 1060 and Nvidia drivers 384

* Named the cat Untitled, chose all options other than "how do I get out of here?" and went for "I'm not leaving you" rather than "I love you too"
* Read the notes on the fridge; didn't do anything other than that
* looked at phone
* Moon told a few dad jokes
* Went "anywhere"
* Forgot what it was called but then I went to the place that's not work or the clinic. The graveyard place I think?
* **At this point the screen goes black. I can see my mouse and the mouse changes to the target cursor when I hover over things, and there's the time in the top-right. I hit esc and the pause menu showed up normally, though the background was black as usual. I could click on areas and I managed to spam-click and advance the story, though I had no idea what I was doing.**
* Chose to survive.

I hope this can help you, sorry if any parts were too vague! I'm working off of memory here. Great game, though, and I love your stuff!

**Comment by zephyo** [comment]
Hi!! Thanks for the report. Just saw this. I'll look into it sometime this week. And thank you for loving my stuff <3 <3 ^_^

**Comment by zephyo** [comment]
Think I fixed it! Lmk if you still get that
